# Pre-commit configuration file,
# when Streamlit's pre-commit detects that one of the linters has failed,
# it automatically lints the files and does not allow the commit to pass.
# Please review the changes after lint has failed and commit them again,
# the second commit should pass,
# because the files were linted after trying to do the first commit.
repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
          # Configure Black to support only syntax supported by the minimum supported Python version in setup.py.
          - --target-version=py37
        files: \.py$|\.pyi$
  - repo: local
    hooks:
      # Script ./scripts/run_in_subdirectory.py was used to work around a
      # known problem with hooks in subdirectories when pass_filenames option
      # is set to true
      # See: https://github.com/pre-commit/pre-commit/issues/1417
      - id: prettier
        name: Prettier
        entry: ./scripts/run_in_subdirectory.py frontend/ yarn prettier --write
        files: ^frontend/.*(.js|\.jsx|\.ts|\.tsx)$
        language: node
        pass_filenames: true
      - id: typecheck
        name: Typecheck
        entry: yarn --cwd frontend tsc --noEmit
        files: \.js$|\.jsx$|\.ts$|\.tsx$
        language: node
        pass_filenames: false
      - id: eslint
        name: Eslint
        entry: ./scripts/run_in_subdirectory.py frontend/ yarn lint -- --fix
        files: ^frontend/src/.*(.js|\.jsx|\.ts|\.tsx)$
        language: node
        pass_filenames: true
      - id: license-headers
        name: Checks that all files have the required license headers
        entry: ./scripts/check_license_headers.py
        language: system
        always_run: true
        pass_filenames: false
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: insert-license
        name: Add license for all (S)CSS/JS(X)/TS(X) files
        files: \.(s?css|jsx?|tsx?)$
        args:
          - --comment-style
          - "/**| *| */"
          - --license-filepath
          - scripts/license-template.txt
          - --fuzzy-match-generates-todo
        exclude: |
          (?x)
          /vendor/
          |^component-lib/declarations/apache-arrow
          |^frontend/src/assets/css/variables\.scss
      - id: insert-license
        name: Add license for all Proto files
        files: \.proto$
        args:
          - --comment-style
          - "/**!| *| */"
          - --license-filepath
          - scripts/license-template.txt
          - --fuzzy-match-generates-todo
        exclude: |
          (?x)
          /vendor/
          |^component-lib/declarations/apache-arrow
          |^proto/streamlit/proto/openmetrics_data_model\.proto
      - id: insert-license
        name: Add license for all shell files
        files: \.sh$
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - scripts/license-template.txt
          - --fuzzy-match-generates-todo
        exclude: |
          (?x)
          /vendor/
          |^component-lib/declarations/apache-arrow
      - id: insert-license
        name: Add license for all Python files
        files: \.py$|\.pyi$
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - scripts/license-template.txt
          - --fuzzy-match-generates-todo
        exclude: |
          (?x)
          /vendor/
          |^component-lib/declarations/apache-arrow
          |^lib/tests/isolated_asyncio_test_case\.py$
      - id: insert-license
        name: Add license for all HTML files
        files: \.html$
        args:
          - --comment-style
          - "<!--||-->"
          - --license-filepath
          - scripts/license-template.txt
          - --fuzzy-match-generates-todo
        exclude: |
          (?x)
          /vendor/
          |^component-lib/declarations/apache-arrow
