# Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Pre-commit configuration file,
# when Streamlit's pre-commit detects that one of the linters has failed,
# it automatically lints the files and does not allow the commit to pass.
# Please review the changes after lint has failed and commit them again,
# the second commit should pass,
# because the files were linted after trying to do the first commit.
repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
          # Configure Black to support only syntax supported by the minimum supported Python version in setup.py.
          - --target-version=py37
        files: \.py$|\.pyi$
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --filter-files
        exclude: ^lib/streamlit/__init__\.py$
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        args:
          - "--in-place"
          - "--ignore-init-module-imports"
          - "--ignore-pass-after-docstring"
          - "--remove-unused-variables"
  - repo: local
    hooks:
      # Script ./scripts/run_in_subdirectory.py was used to work around a
      # known problem with hooks in subdirectories when pass_filenames option
      # is set to true
      # See: https://github.com/pre-commit/pre-commit/issues/1417
      - id: prettier
        name: Prettier
        entry: ./scripts/run_in_subdirectory.py frontend/ yarn prettier --write
        files: ^frontend/.*(.js|\.jsx|\.ts|\.tsx)$
        exclude: /vendor/
        language: node
        pass_filenames: true
      - id: typecheck
        name: Typecheck
        entry: yarn --cwd frontend tsc --noEmit
        files: \.js$|\.jsx$|\.ts$|\.tsx$
        language: node
        pass_filenames: false
      - id: eslint
        name: Eslint
        entry: ./scripts/run_in_subdirectory.py frontend/ yarn lint -- --fix
        files: ^frontend/src/.*(.js|\.jsx|\.ts|\.tsx)$
        language: node
        pass_filenames: true
      - id: license-headers
        name: Checks that all files have the required license headers
        entry: ./scripts/check_license_headers.py
        language: system
        always_run: true
        pass_filenames: false
      - id: no-relative-imports
        language: pygrep
        name: No relative imports
        description: Streamlit style is to use absolute imports only (except docs building)
        entry: "^\\s*from\\s+\\."
        pass_filenames: true
        files: \.py$
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: insert-license
        name: Add license for all (S)CSS/JS(X)/TS(X) files
        files: \.(s?css|jsx?|tsx?)$
        args:
          - --comment-style
          - "/**| *| */"
          - --license-filepath
          - scripts/license-template.txt
          - --fuzzy-match-generates-todo
        exclude: |
          (?x)
          /vendor/
          |^component-lib/declarations/apache-arrow
          |^frontend/src/assets/css/variables\.scss
      - id: insert-license
        name: Add license for all Proto files
        files: \.proto$
        args:
          - --comment-style
          - "/**!| *| */"
          - --license-filepath
          - scripts/license-template.txt
          - --fuzzy-match-generates-todo
        exclude: |
          (?x)
          /vendor/
          |^component-lib/declarations/apache-arrow
          |^proto/streamlit/proto/openmetrics_data_model\.proto
      - id: insert-license
        name: Add license for all shell files
        files: \.sh$
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - scripts/license-template.txt
          - --fuzzy-match-generates-todo
        exclude: |
          (?x)
          /vendor/
          |^component-lib/declarations/apache-arrow
      - id: insert-license
        name: Add license for all Python files
        files: \.py$|\.pyi$
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - scripts/license-template.txt
          - --fuzzy-match-generates-todo
        exclude: |
          (?x)
          /vendor/
          |^component-lib/declarations/apache-arrow
          |^lib/tests/isolated_asyncio_test_case\.py$
      - id: insert-license
        name: Add license for all HTML files
        files: \.html$
        args:
          - --comment-style
          - "<!--||-->"
          - --license-filepath
          - scripts/license-template.txt
          - --fuzzy-match-generates-todo
        exclude: |
          (?x)
          /vendor/
          |^component-lib/declarations/apache-arrow
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)
          ^frontend/src/assets/
          |^NOTICES$
          |^proto/streamlit/proto/openmetrics_data_model.proto$
          |\.snap$

  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: 6.1.1
  #   hooks:
  #     - id: pydocstyle
  #       name: Run pydocstyle
  #       args:
  #         - --convention=numpy
  #         - --add-ignore=D100,D101,D104,D105,D106,D107
  #         - --add-select=D417
  #         - --match-dir=(lib\/streamlit\/)(?!vendor)(?!watcher)
