name: Javascript Tests

on: [push, pull_request]

jobs:
  js_tests:

    runs-on: ubuntu-latest

    permissions:
      actions: read

    defaults:
      run:
        shell: bash -ileo pipefail {0}

    steps:
      - name: Checkout Streamlit code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: ./.github/actions/update_submodules
      - uses: ./.github/actions/pre_cache
      - uses: ./.github/actions/pre_make
      - uses: ./.github/actions/make_init
      - name: Run make develop
        run: |
          source venv/bin/activate
          make develop
      - name: Run frontend tests
        run: |
          source venv/bin/activate
          make jstest