name: Test for python workflow call

on:
  schedule:
    # Run job at 12.30pm PST
    - cron:  '30 12 * * *'

jobs:
  python:
    uses: ./.github/workflows/python-versions.yml
    with:
      ref: ${{ github.ref_name }}
    secrets:
      PARAMETER_PASSWORD: ${{ secrets.PARAMETER_PASSWORD }}
